name: build

on: 
  workflow_dispatch:

jobs:
  Setup:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target: [K2P]
        toolchain: [mipsel-linux-musl]
    steps:
      - uses: actions/checkout@main
      - uses: hendrikmuhs/ccache-action@main
        with:
          key: ${{ matrix.target }}-${{ matrix.toolchain }}
          
      - name: Setup
        run: |
          sudo apt update
          sudo apt install libtool-bin gperf python3-docutils autopoint gettext ccache
          
      - name: Build
        run: |
          make ${{ matrix.target }} TOOLCHAIN=${{ matrix.toolchain }}
          if [ "${{ matrix.target }}" = "K2P-NANO" ]; then
            image=$(ls trunk/images/*.trx)
            mv $image $(echo $image | sed 's/K2P/K2P-NANO/')
          fi
          
      - name: Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: ${{ env.TAG_NAME }} # 指定标签名，会自动创建此标签
          files: trunk/images/*.trx # 直接指定要发布的构件路径
